pref("extensions.thunderlink.custom-tl-string-1-title", "Copy plain TL to clipboard");
pref("extensions.thunderlink.custom-tl-string-1", "<thunderlink>");
pref("extensions.thunderlink.custom-tl-string-1-tagcheckbox", false);
pref("extensions.thunderlink.custom-tl-string-1-tag", 1);
pref("extensions.thunderlink.custom-tl-string-2-title", "Copy call to executable + TL to clipboard");
pref("extensions.thunderlink.custom-tl-string-2", "<tbexe> <thunderlink>");
pref("extensions.thunderlink.custom-tl-string-2-tagcheckbox", false);
pref("extensions.thunderlink.custom-tl-string-2-tag", 1);
pref("extensions.thunderlink.custom-tl-string-3-title", "Custom String 3");
pref("extensions.thunderlink.custom-tl-string-3", "<thunderlink>");
pref("extensions.thunderlink.custom-tl-string-3-tagcheckbox", false);
pref("extensions.thunderlink.custom-tl-string-3-tag", 1);
pref("extensions.thunderlink.custom-tl-string-4-title", "Custom String 4");
pref("extensions.thunderlink.custom-tl-string-4", "<thunderlink>");
pref("extensions.thunderlink.custom-tl-string-4-tagcheckbox", false);
pref("extensions.thunderlink.custom-tl-string-4-tag", 1);
pref("extensions.thunderlink.open-tl-behaviour", "bySelecting");
