pref("extensions.thunderlink.custom-tl-string-1-title", "thunderlink");
pref("extensions.thunderlink.custom-tl-string-1", "<thunderlink>");
pref("extensions.thunderlink.custom-tl-string-1-tagcheckbox", false);
pref("extensions.thunderlink.custom-tl-string-1-tag", 1);
pref("extensions.thunderlink.custom-tl-string-2-title", "local cmd");
pref("extensions.thunderlink.custom-tl-string-2", "<tbexe> <thunderlink>");
pref("extensions.thunderlink.custom-tl-string-2-tagcheckbox", false);
pref("extensions.thunderlink.custom-tl-string-2-tag", 1);
pref("extensions.thunderlink.custom-tl-string-3-title", "RFC 2392");
pref("extensions.thunderlink.custom-tl-string-3", "mid:<messageid>");
pref("extensions.thunderlink.custom-tl-string-3-tagcheckbox", false);
pref("extensions.thunderlink.custom-tl-string-3-tag", 1);
pref("extensions.thunderlink.custom-tl-string-4-title", "Mac Mail");
pref("extensions.thunderlink.custom-tl-string-4", "message://%3c<messageid>%3e");
pref("extensions.thunderlink.custom-tl-string-4-tagcheckbox", false);
pref("extensions.thunderlink.custom-tl-string-4-tag", 1);
pref("extensions.thunderlink.custom-tl-string-5-title", "Custom String 5");
pref("extensions.thunderlink.custom-tl-string-5", "<thunderlink>");
pref("extensions.thunderlink.custom-tl-string-5-tagcheckbox", false);
pref("extensions.thunderlink.custom-tl-string-5-tag", 1);
pref("extensions.thunderlink.custom-tl-string-6-title", "Custom String 6");
pref("extensions.thunderlink.custom-tl-string-6", "<thunderlink>");
pref("extensions.thunderlink.custom-tl-string-6-tagcheckbox", false);
pref("extensions.thunderlink.custom-tl-string-6-tag", 1);
pref("extensions.thunderlink.custom-tl-string-7-title", "Custom String 7");
pref("extensions.thunderlink.custom-tl-string-7", "<thunderlink>");
pref("extensions.thunderlink.custom-tl-string-7-tagcheckbox", false);
pref("extensions.thunderlink.custom-tl-string-7-tag", 1);
pref("extensions.thunderlink.custom-tl-string-8-title", "Custom String 8");
pref("extensions.thunderlink.custom-tl-string-8", "<thunderlink>");
pref("extensions.thunderlink.custom-tl-string-8-tagcheckbox", false);
pref("extensions.thunderlink.custom-tl-string-8-tag", 1);
pref("extensions.thunderlink.open-tl-behaviour", "bySelecting");
